from setuptools import setup, find_packages

setup(
    name='PyAutoload',
    version='0.1.0-alpha.1',
    packages=find_packages(where='src'),
    package_dir={'': 'src'},
    install_requires=['watchdog>=3.0.0'],
    author='David Teren',
    author_email='example@example.com',
    description='A Python autoloading library inspired by Zeitwerk.',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/user/pyautoload',
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ],
    python_requires='>=3.6',
    keywords='autoloading, module, import, zeitwerk, python, dependency-tracking',
)
