blank_issues_enabled: false
contact_links:
  - name: PyAutoload Documentation
    url: https://github.com/your-username/PyAutoload/blob/main/README.md
    about: Please check the documentation before reporting an issue
  - name: GitHub Discussions
    url: https://github.com/your-username/PyAutoload/discussions
    about: Please ask and answer questions here.
